### ISSUE TITLE
Alignment issue during training

### ISSUE THREAD

**Issue by nikki509** [IyatomiLab/LeafGAN#10]
Step1: python train.py --dataroot /path/to/healthy2brownspot --name healthy2brownspot_leafGAN --model leaf_gan

When I am testing on my dataset, while running i got the below error:

Traceback (most recent call last):
  File "train.py", line 28, in <module>
    opt = TrainOptions().parse()   # get training options
  File "/kaggle/working/LeafGAN/options/base_options.py", line 116, in parse
    opt = self.gather_options()
  File "/kaggle/working/LeafGAN/options/base_options.py", line 76, in gather_options
    model_option_setter = models.get_option_setter(model_name)
  File "/kaggle/working/LeafGAN/models/__init__.py", line 50, in get_option_setter
    model_class = find_model_using_name(model_name)
  File "/kaggle/working/LeafGAN/models/__init__.py", line 33, in find_model_using_name
    modellib = importlib.import_module(model_filename)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/kaggle/working/LeafGAN/models/leaf_gan_model.py", line 54
    self.is_using_mask = opt.dataset_mode == "unaligned_masked"
                                                              ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by huuquan1994** [comment]
@nikki509 

The `TabError: inconsistent use of tabs and spaces in indentation` occurs when the Python code has all the tabs and spaces mixed up.
If you use Sublime Text, you can fix this by using `View -> Indentation -> Convert Indentations to Tabs`

For more details, please refer to this https://www.stechies.com/taberror-inconsistent-tabs-spaces-indentation/

**Comment by nikki509** [comment]
Thank you
